### ISSUE TITLE
[Remoto] [Engenheiro de Software Java Pleno Remota com inglês avançado para conversação] na [HunterHunter]

### ISSUE THREAD

**Issue by ErickaMB** [soujava/vagas-java#1684]
[Engenheiro de Software Java Pleno Remota com inglês avançado para conversação] - Remoto. R$ 6 mil a 7 mil CLT.

Requisitos:

Formação em Análise e Desenvolvimento de Sistemas, Ciências da Computação ou afins.
Desenvolvimento back-end utilizando Java aplicando conceitos de arquitetura de software (como DDD - Domain Driven Design), bons design-patterns e desenvolvimento de testes integrados e automatizados utilizando bibliotecas como Mockito e JUnit.
Conhecimentos técnicos necessários:
Java (programação orientada a objetos) 3+ anos de experiência
Maven (gerenciador de pacotes)
Git (versionamento de código)
Docker (containerização e virtualização)
Microservices (arquitetura de software)
API REST e SOAP (protocolos de comunicação)
JSON e XML (estrutura de dados)
Message Broker (sistemas de mensageria como RabbitMQ, AWS SQS, Kafka ou Google Pub/Sub).

Ferramentas adicionais que utilizamos:
DataDog (para monitoramento de forma ativa)
JIRA e Confluence (controle de tasks e documentações internas)
GitHub (ferramenta visual para Git)
Travis CI (automação de builds)
Slack (para comunicação).

Nosso time é apaixonado por tecnologia, trabalha com base na ética, transparência, respeito e com muita garra para alcançar os objetivos e superar nossos desafios.
Estamos buscando Engenheiro(a) de Software para compor nosso time!

Esse squad possui atuação global, ou seja, temos membros do time em diversos lugares do globo, principalmente no Brasil, Canadá, Estados Unidos e Índia, portanto, trabalhar com diferentes fuso-horários também faz parte do nosso dia a dia. Somos um dos principais squads fornecedor do produto para nossos clientes (internos e externos) portanto qualidade no desenvolvimento e entrega é um tema indiscutível para nós. Interação com os demais times internos também é esperado, como: time de QA (quality assurance), time de documentação, time de produto e demais times de engenharia.

As atividades do seu dia a dia serão:

Nós construímos um produto, e produto nunca acaba! Dessa forma, trabalhamos com entrega contínua, isso significa fazer parte de uma squad que roda metodologia ágil (scrum) com sprints definidos e entregas para produção de forma incremental e contínua (utilizando pipelines de CI e CD). Será responsável por todas as fases de desenvolvimento de software (SDLC - Software Development Life Cycle) o que inclui a participação nas sessões de Grooming para entendimento e definição da feature (em como aquela feature deve ser desenvolvida), o desenvolvimento propriamente dito, processos de Code Review, liderar e direcionar os testes com o time de QAs, fornecer insumos para o time de documentação, acompanhar a entrega da feature para os ambientes de produção e atuação em melhorias ou correções de bugs se necessário (nós não gostamos de bugs). Principais objetivos diários:
Trabalhar na construção de componentes que habilitem a comunicação/conexão com tecnologias (protocolos de comunicação) e sistemas de mercado de forma global.
Trabalhar na construção de tools internas para automatizar a maior parte do trabalho manual que fazemos em busca de sempre deixar a nossa vida mais simples e mais prática.

Benefícios:

PARCERIA COM INSTITUIÇÕES DE ENSINO PARA DESCONTO EM CURSOS PORTAIS DE DESCONTO PLATAFORMA DE TREINAMENTOS VOLTADOS À SOFT SKILLS BENEFÍCIO FLEXÍVEL ASSISTÊNCIA ODONTOLÓGICA PROGRAMA DE ASSISTÊNCIA AO COLABORADOR (PAE) ASSISTÊNCIA MÉDICA TOTAL PASS VALE ALIMENTAÇÃO / REFEIÇÃO AUXÍLIO CRECHE SEGURO DE VIDA PARTICIPAÇÃO NOS LUCROS DAY OFF NO MÊS DO ANIVERSÁRIO AUXÍLIO HOME OFFICE SHORT FRIDAY NO VERÃO.

Sobre:
Somos a plataforma em nuvem para integração de dados entre sistemas e APIs (iPaaS) líder da América Latina. Ajudamos empresas de todos os tamanhos e de todos os segmentos a tornarem-se digitais de verdade com uma operação 100% conectada. A partir de uma única interface, nossa plataforma automatiza fluxos de integração de dados entre sistemas, processos, departamentos e organizações, eliminando a necessidade de processos manuais.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [[https://www.linkedin.com/in/erickamarquesb/]](https://www.linkedin.com/in/erickamarquesb/%5D)

**Comment by TasksResolver** [comment]
🌹🌹Hello, There!🌹🌹
Here is a good fit candidate. So you don't need to find another someone.
I will provide you with the best solution for your project.
Please lets start your business with me.
As a software engineer, I developed a module to manage building automation network system devices with Java from May 2014 to August 2014. It was a PLC which had equipped with 128 terminal sensors. I got the values of the device in real-time and stored them in the MariaDB database, and was able to control some of the terminal endpoints as well. During the time I was working on the project, I was really excited and really learned a lot.

I have also been able to develop a basic React + Three + Next Project in light of web development trends such as virtual exhibitions for the past three years. I have been able to solve many technical problems while encountering rather complicated theories and techniques such as the construction and implementation of 3D space. 

I have been developing about 10 UX/UI websites using the latest frameworks(BE: Node.js + NestJs(ExpressJs) + MongoDB & APIs integration & FE: React Framework(Next.js) + Tailwind CSS( plus Sass) + Typescript) over the past two years, and Node.js and NestJS backend projects have now become my daily business parts.

I am interested in building an artificial intelligence chatbot and am trying it out somewhat.

This is my Github url: https://github.com/TasksResolver

I prefer to commit deeply to a project rather than bragging about myself.

I am looking forward to the opportunity to work with you.

Thank you.

Vadym.
