### ISSUE TITLE
INMETRICS - Pessoa Desenvolvedora Java Sênior - Híbrido - São Paulo

### ISSUE THREAD

**Issue by nandagomess** [soujava/vagas-java#1686]
>>>>>> Pessoa Desenvolvedora Java Sênior - Híbrido - São Paulo -https://inmetrics.gupy.io/jobs/4716472

Atividades e Responsabilidades
Modelo de trabalho: Híbrido em Interlagos (SP) - Presencialmente 3x na semana | CLT 💻

REQUISITOS E QUALIFICAÇÕES

> Experiência como desenvolvedor sênior em aplicações backend usando Java e frameworks Spring / Spring Boot.

> Conhecimento em arquiteturas de microserviços e sua implementação usando frameworks Spring (Spring Cloud / Netflix OSS) Experiência em lidar com grandes volumes de dados e desafios de escalabilidade em aplicações distribuídas.

> Pró-atividade; Habilidades de comunicação entre as diferentes áreas interessadas;
> Conhecimento em metodologias ágeis;

> Conhecimento em BDD;

> Microserviços em java usando ecossistema do Spring;

> Experiência com serviços de mensageria (kafka e rabbit MQ);

> Experiência com Cloud (AWS e Azure)

> Conhecimento em Observabilidade Boas praticas de desenvolvimento (SOLID, Parthners etc);

> Experiência com cultura DEVOPS;

> Conhecimentos com DB's relacionais e não relacionais (Postgree,Oracle e MongoDB)

Requisitos
Familiaridade com containers e ferramentas de conteinerização, como Docker e Kubernetes.

Experiência como engenheiro ou desenvolvedor sênior atuando em plataformas Cloud Cloud AWS ou Azure ou Google Cloud.

Conhecimento em ferramentas de integração contínua e entrega contínua, como Jenkins, Gitlab CI, etc

Ter atuado em sistemas bancários.

**Comment by TasksResolver** [comment]
🌹🌹Hello, There!🌹🌹
Here is a good fit candidate. So you don't need to find another someone.
I will provide you with the best solution for your project.
Please lets start your business with me.
As a software engineer, I developed a module to manage building automation network system devices with Java from May 2014 to August 2014. It was a PLC which had equipped with 128 terminal sensors. I got the values of the device in real-time and stored them in the MariaDB database, and was able to control some of the terminal endpoints as well. During the time I was working on the project, I was really excited and really learned a lot.

I have also been able to develop a basic React + Three + Next Project in light of web development trends such as virtual exhibitions for the past three years. I have been able to solve many technical problems while encountering rather complicated theories and techniques such as the construction and implementation of 3D space. 

I have been developing about 10 UX/UI websites using the latest frameworks(BE: Node.js + NestJs(ExpressJs) + MongoDB & APIs integration & FE: React Framework(Next.js) + Tailwind CSS( plus Sass) + Typescript) over the past two years, and Node.js and NestJS backend projects have now become my daily business parts.

I am interested in building an artificial intelligence chatbot and am trying it out somewhat.

This is my Github url: https://github.com/TasksResolver

I prefer to commit deeply to a project rather than bragging about myself.

I am looking forward to the opportunity to work with you.

Thank you.

Vadym.
