### ISSUE TITLE
Dev. Full Stack (Flutter + C#)

### ISSUE THREAD

**Issue by vitorpety** [soujava/vagas-java#1693]
**DESCRIÇÃO DA VAGA:**

Quem é coder agora também pode ser #Zallper!

Se você entrega tudo e mais um pouco, desde a construção dos serviços de back-end até a codificação dos layouts e integração com os serviços criados, chegou na vaga certa.

Já pensou em desenvolver sua carreira na Zallpy? A gente sim!

Nesta oportunidade, você estará atuando em projeto internacional junto de uma squad ágil de um dos 3 maiores players do setor automotivo.

Se identificou? Queremos te conhecer!

Aproveite para conhecer melhor a Zallpy Digital clicando aqui 👉 https://zallpy.com/ 😉

**RESPONSABILIDADES E ATRIBUIÇÕES:**

- Desenvolvimento de APIs para aplicações móveis
- Atuar em ferramentas de CI/CD/DevOps como: Jenkins, Concourse, GitHub, Bitbucket, SonarQube e Artifactory
- Desenvolvimento utilizando orquestração de containers como Docker e Kubernetes
- REQUISITOS E QUALIFICAÇÕES
- Necessário nível avançado ou fluente de inglês conversação e escrita.
- Sólida experiência em desenvolvimento de software no back e frontend
- Experiência com desenvolvimento nas linguagens Dart/Flutter; C# (.NET)
- Experiência com desenvolvimento nas linguagens Nodejs/Typescript/NestJS Framework
- Desenvolvimento de aplicações na nuvem Azure
- Experiência com Terraform

INFORMAÇÕES ADICIONAIS:

Será um diferencial:

- Experiência usando Github, Jenkins, Sonar
- Experiência com Grafana, Kibana
- Experiência com orquestração de containers como Docker e Kubernetes.

Enviar currículo para: recrutamento@zallpy.com

**Comment by TasksResolver** [comment]
🌹🌹Hello, There!🌹🌹
Here is a good fit candidate. So you don't need to find another someone.
I will provide you with the best solution for your project.
Please lets start your business with me.
As a software engineer, I developed a module to manage building automation network system devices with Java from May 2014 to August 2014. It was a PLC which had equipped with 128 terminal sensors. I got the values of the device in real-time and stored them in the MariaDB database, and was able to control some of the terminal endpoints as well. During the time I was working on the project, I was really excited and really learned a lot.

I have also been able to develop a basic React + Three + Next Project in light of web development trends such as virtual exhibitions for the past three years. I have been able to solve many technical problems while encountering rather complicated theories and techniques such as the construction and implementation of 3D space. 

I have been developing about 10 UX/UI websites using the latest frameworks(BE: Node.js + NestJs(ExpressJs) + MongoDB & APIs integration & FE: React Framework(Next.js) + Tailwind CSS( plus Sass) + Typescript) over the past two years, and Node.js and NestJS backend projects have now become my daily business parts.

I am interested in building an artificial intelligence chatbot and am trying it out somewhat.

This is my Github url: https://github.com/TasksResolver

I prefer to commit deeply to a project rather than bragging about myself.

I am looking forward to the opportunity to work with you.

Thank you.

Vadym.

**Comment by TasksResolver** [comment]
🌹🌹Hello, There!🌹🌹
Here is a good fit candidate. So you don't need to find another someone.
I will provide you with the best solution for your project.
Please lets start your business with me.
As a software engineer, I developed a module to manage building automation network system devices with Java from May 2014 to August 2014. It was a PLC which had equipped with 128 terminal sensors. I got the values of the device in real-time and stored them in the MariaDB database, and was able to control some of the terminal endpoints as well. During the time I was working on the project, I was really excited and really learned a lot.

I have also been able to develop a basic React + Three + Next Project in light of web development trends such as virtual exhibitions for the past three years. I have been able to solve many technical problems while encountering rather complicated theories and techniques such as the construction and implementation of 3D space. 

I have been developing about 10 UX/UI websites using the latest frameworks(BE: Node.js + NestJs(ExpressJs) + MongoDB & APIs integration & FE: React Framework(Next.js) + Tailwind CSS( plus Sass) + Typescript) over the past two years, and Node.js and NestJS backend projects have now become my daily business parts.

I am interested in building an artificial intelligence chatbot and am trying it out somewhat.

This is my Github url: https://github.com/TasksResolver

I prefer to commit deeply to a project rather than bragging about myself.

I am looking forward to the opportunity to work with you.

Thank you.

Vadym.
